[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = [
  "chmod +x ./gradlew",
  "./gradlew clean bootJar --no-daemon -x test"
]

[start]
cmd = "java -jar build/libs/dental-saas-mvp-0.0.1-SNAPSHOT.jar"
