[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = [
  "cd backend && ./gradlew clean bootJar --no-daemon -x test"
]

[start]
cmd = "java -jar backend/build/libs/dental-saas-mvp-0.0.1-SNAPSHOT.jar"
